import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "material-symbols";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            // position: "relative",
            backgroundColor: "#101019",
            display: "flex",
            justifyContent: "flex-start",
            gap: "2em",
            padding: "1rem",
            marginBottom: "1rem",
            top: 0,
            left: 0,
          }}
        >
          <Link href="/">
            <span className="material-symbols-outlined testing">home</span>
          </Link>
          <Link href="/users">
            <span className="material-symbols-outlined">account_circle</span>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
