import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import path from "node:path";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            position: "absolute",
            backgroundColor: "midnight",
            display: "flex",
            top: 0,
            left: 0,
          }}
        >
          <Link href="/">HOME</Link>
          <Link href="/users">USERS</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
